/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: { "surface-variant": "#dde1ff", "tertiary-container": "#9a928d", "surface-container-highest": "#dde1ff", "on-error": "#ffffff", "inverse-on-surface": "#f0efff", "on-secondary-fixed-variant": "#404561", "on-tertiary-fixed-variant": "#4b4642", "on-secondary": "#ffffff", "tertiary-fixed": "#eae1db", "inverse-primary": "#ffb59d", "surface-dim": "#d4d8f7", "inverse-surface": "#2a2f47", "primary-fixed-dim": "#ffb59d", "secondary-fixed": "#dee1ff", "on-primary": "#ffffff", "tertiary-fixed-dim": "#cec5bf", "surface-container": "#ececff", "on-error-container": "#93000a", "primary-container": "#ff5e1e", "outline": "#8f7066", "secondary-fixed-dim": "#c1c4e6", "secondary-container": "#d7dbfd", "surface-tint": "#ff5e1e", "primary-fixed": "#ffdbd0", "on-background": "#151a31", "on-primary-container": "#561600", "on-secondary-container": "#5b5f7c", "surface-container-lowest": "#ffffff", "on-surface": "#151a31", "charcoal-navy": "#0E132C", "on-surface-variant": "#5b4138", "success-green": "#10B981", "surface": "#fbf8ff", "error": "#ba1a1a", "on-tertiary-fixed": "#1f1b17", "surface-bright": "#fbf8ff", "on-primary-fixed-variant": "#832700", "error-container": "#ffdad6", "warm-surface": "#FEF4EE", "on-primary-fixed": "#390c00", "border-subtle": "#E5E7EB", "on-secondary-fixed": "#151a33", "surface-container-high": "#e4e7ff", "background": "#fbf8ff", "on-tertiary-container": "#302b28", "outline-variant": "#e3beb3", "electric-citrus": "#ff5e1e", "tertiary": "#635d59", "secondary": "#585d7a", "on-tertiary": "#ffffff", "primary": "#ff5e1e", "surface-container-low": "#f3f2ff" },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      spacing: { "gutter-mobile": "1rem", "space-md": "1rem", "space-xl": "2.5rem", "gutter": "1.5rem", "space-xs": "0.25rem", "space-2xl": "4rem", "margin": "2rem", "margin-mobile": "1rem", "space-sm": "0.5rem", "space-lg": "1.5rem" },
      fontFamily: { "headline-sm": ["Cairo"], "body-lg": ["Cairo"], "headline-md": ["Cairo"], "body-sm": ["Cairo"], "display-hero": ["Cairo"], "label-lg": ["Cairo"], "headline-lg": ["Cairo"], "body-md": ["Cairo"], "label-md": ["Cairo"], "display-hero-mobile": ["Cairo"], "headline-xl-mobile": ["Cairo"], "headline-xl": ["Cairo"], "code-badge": ["Cairo"] },
      fontSize: { "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }], "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }], "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }], "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }], "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700" }], "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }], "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }], "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }], "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }], "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }], "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }], "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }], "code-badge": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }] }
    }
  },
  plugins: [],
};
